owner: seongland
repo: seongland-status

sites:
  - name: Seongland
    url: https://www.seongland.com
  - name: Seongland Account
    url: https://account.seongland.com
  - name: Pointland
    url: https://point.seongland.com
  - name: Seongland Live
    url: https://live.seongland.com
  - name: Seongland Wiki
    url: https://doc.seongland.com

status-website:
  cname: status.seongland.com
  logoUrl: https://seongland.com/seongland.svg
  name: Status
  introTitle: "Seongland Server Status"
  introMessage: Seongland Web Service status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

