owner: seongland
repo: statusland

sites:
  - name: Seongland
    url: https://www.seongland.com
  - name: Texonom
    url: https://texonom.com
  - name: Pointland
    url: https://point.seongland.com

status-website:
  cname: status.seongland.com
  logoUrl: https://seongland.com/seongland.svg
  name: Status
  introTitle: "Seongland Server Status"
  introMessage: Seongland Web Service status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
